[build]
builder="NIXPACKS"

[deploy]
numReplicas=1
startCommand="gunicorn -w 4 -b 0.0.0.0:8000 app:app"
sleepApplication=false
restartPolicyType="ON_FAILURE"
restartPolicyMaxRetries=10

[phases.setup]
pkgs = ["python311"]
